# Generated by Django 4.1.3 on 2022-11-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('date_limited', models.DateField()),
                ('asignado_a', models.CharField(max_length=20)),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.priority')),
            ],
        ),
    ]
