# Generated by Django 4.1.3 on 2022-11-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='taskModel',
            new_name='Task_Model',
        ),
    ]
